version: '3.0'

services:
  postgre:
   image: postgres:12.17
   ports: 
    - "5432:5432"
   environment:
    POSTGRES_PASSWORD: Pg123
    POSTGRES_USER: kubenews
    POSTGRES_DB: kubenews
   networks:
   - kube_news_network
   volumes:
    - postgresql_volume:/var/lib/postgresql/data
    
    
  kube_new_front:
   image: giovanniplima/kube-news:v1
   build:
     context: .
     dockerfile: Dockerfile
   container_name: front_end
   depends_on:
    - postgre
   ports:
    - "8080:8080"
   environment:
    DB_DATABASE: kubenews
    DB_USERNAME: kubenews
    DB_PASSWORD: Pg123
    DB_HOST: postgre
   networks:
    - kube_news_network

networks:
 kube_news_network:
  driver: bridge

volumes:
 postgresql_volume:
  

  