version: '3.0'

services:
  postgre:
   image: postgres:12.17
   ports: 
    - "5432:5432"
   environment:
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_DB: ${POSTGRES_DB}
   networks:
   - kube_news_network
   volumes:
    - postgresql_volume:/var/lib/postgresql/data
    
    
  kube_new_front:
   image: giovannipajeu/kube-dev-news:v1
   build:
     context: .
     dockerfile: Dockerfile
   container_name: front_end
   depends_on:
    - postgre
   ports:
    - "8080:8080"
   environment:
    DB_DATABASE: ${POSTGRES_PASSWORD}
    DB_USERNAME: ${POSTGRES_USER}
    DB_PASSWORD: ${POSTGRES_DB}
    DB_HOST: postgre
   networks:
    - kube_news_network

networks:
 kube_news_network:
  driver: bridge

volumes:
 postgresql_volume:
  driver: local
  

  