name: Deploy To Kubernetes

on:
 push:
  branches: ["main"]


jobs:
  CI:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4.1.3
     - name: Docker Login       
       uses: docker/login-action@v3.1.0
       with:
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{secrets.DOCKER_PASSWORD}}
     - name: Docker Build And Push
       uses: docker/build-push-action@v5.3.0
       with:
        context: ./src
        file: ./src/Dockerfile
        pull: true
        tags: giovanniplima/kube-dev-news:v1
              giovanniplima/kube-dev-news:latest       
     
