name: Deploy To Kubernetes

on:
 push:
  branches: ["main"]


jobs:
  CI:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v4.1.3
     - name: Docker Login       
       uses: docker/login-action@v3.1.0
       with:
        username: ${{secrets.DOCKER_LOGIN}}
        password: ${{secrets.DOCKER_PASSWORD}}
     - name: Docker Build And Push
       uses: docker/build-push-action@v5.3.0
       with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          giovannipajeu/kube-dev-news:${{github.run_number}}
          giovannipajeu/kube-dev-news:latest       
  
  CD:
   runs-on: ubuntu-latest
   needs: [CI]

   steps:
     - uses: actions/checkout@v4.1.3

     - name: Set Context Kubernetes
       uses: Azure/k8s-set-context@v3.0
       with:
        method: kubeconfig
        kubeconfig: ${{secrets.K8S_CONFIG}}
     - name: Deploy to Kubernetes Cluster
       uses: Azure/k8s-deploy@v4
       with:
        images: giovannipajeu/kube-dev-news:${{github.run_number}}
        manifests: |
         ./src/deployment.yaml
